"""initial

Revision ID: d1e2176e204e
Revises: 
Create Date: 2026-03-17 16:24:15.521216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2176e204e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('soulbolt_account_id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('external_link', sa.String(), nullable=True),
    sa.Column('influence_score_cache', sa.Integer(), nullable=False),
    sa.Column('score_cached_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle'),
    sa.UniqueConstraint('soulbolt_account_id')
    )
    op.create_index('ix_creator_profiles_handle', 'creator_profiles', ['handle'], unique=False)
    op.create_index('ix_creator_profiles_soulbolt_account_id', 'creator_profiles', ['soulbolt_account_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('contact_method', sa.String(), nullable=False),
    sa.Column('contact_value', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'slug', name='uq_creator_slug')
    )
    op.create_index('ix_listings_creator_id', 'listings', ['creator_id'], unique=False)
    op.create_index('ix_listings_status', 'listings', ['status'], unique=False)
    op.create_table('listing_index',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_index_creator_id', 'listing_index', ['creator_id'], unique=False)
    op.create_index('ix_listing_index_published_at', 'listing_index', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_index_published_at', table_name='listing_index')
    op.drop_index('ix_listing_index_creator_id', table_name='listing_index')
    op.drop_table('listing_index')
    op.drop_index('ix_listings_status', table_name='listings')
    op.drop_index('ix_listings_creator_id', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_creator_profiles_soulbolt_account_id', table_name='creator_profiles')
    op.drop_index('ix_creator_profiles_handle', table_name='creator_profiles')
    op.drop_table('creator_profiles')
    # ### end Alembic commands ###
