"""add_indexes

Revision ID: a71646a98146
Revises: 22e1a4742c01
Create Date: 2026-03-17 16:14:42.843772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71646a98146'
down_revision: Union[str, Sequence[str], None] = '22e1a4742c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_creator_profiles_handle', 'creator_profiles', ['handle'], unique=False)
    op.create_index('ix_creator_profiles_soulbolt_account_id', 'creator_profiles', ['soulbolt_account_id'], unique=False)
    op.create_index('ix_listing_index_creator_id', 'listing_index', ['creator_id'], unique=False)
    op.create_index('ix_listing_index_published_at', 'listing_index', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_index_published_at', table_name='listing_index')
    op.drop_index('ix_listing_index_creator_id', table_name='listing_index')
    op.drop_index('ix_creator_profiles_soulbolt_account_id', table_name='creator_profiles')
    op.drop_index('ix_creator_profiles_handle', table_name='creator_profiles')
    # ### end Alembic commands ###
